diyblog/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import *

app_name = 'accounts'
urlpatterns = [
    path('accounts/signup/', signup_page, name='signup'),
    path('accounts/activate/<slug:uidb64>/<slug:token>/', activate_account_page, name='activate'),
    path('accounts/login/', login_page, name='login'),
    path('accounts/logout/', logout_view, name='logout'),


    # Reset Passoword Urls
    path('accounts/reset-password', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'),
         name='reset_password'),
    path('accounts/password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_sent.html'),
         name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_form.html'),
         name='password_reset_confirm'),
    path('accounts/reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_complete'),

    path('', home, name='home'),
     path('blog', blog, name='blog'),
     path('blog_list', blog_list, name='blog_list'),
     path('post_blog',post_blog,name='post_blog'),
     path('blog_detail/<int:blog_id>/', blog_detail, name='blog_detail'),
]


# To update password reset functionality

diyblog/blog/urls.py
from blog import views
from os import name
from django.urls import path
from blog.views import *

urlpatterns = [
    
]

diyblog/diyblog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('blog.urls','blog'), namespace='blog')),
    path('', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    
]

diyblog/blog/models.py
from django.db import models

# Create your models here.

diyblog/blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import redirect, render

# Create your views here.

diyblog/templates/blog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>Blog</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- bootstrap css -->
      <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
      <!-- style css -->
      <link rel="stylesheet" type="text/css" href="{% static 'css/style-index.css' %}">
      <!-- Responsive-->
      <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
      <!-- fevicon -->
      <link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/gif" />
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
      <!-- Tweaks for older IEs-->
      <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
      <!-- owl stylesheets --> 
      <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
      <link rel="stylesoeet" href="{% static 'css/owl.theme.default.min.css' %}">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
   </head>
   <body>
      <!-- header section start -->
      <div class="header_section">
         <div class="container-fluid header_main">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
               <a class="logo" href="#">BLOGSPOT</a>
               <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
               <span class="navbar-toggler-icon"></span>
               </button>
               <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav mr-auto">
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:home' %}">Home</a>
                     </li>
                    
                     
                    
                     <li class="nav-item">
                        <a class="nav-link" href="blog.html">Blog</a>
                     </li>
                    
                    
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                     </li>
                     
                  </ul>
               </div>
            </nav>
         </div>
      </div>
      <!-- blog section start --> 
      <div class="about_section layout_padding">
         <div class="container">
            <div class="row">
               <div class="col-lg-8 col-sm-12">
                  <div class="about_img"><img src="{% static 'images/img-8.png' %}"></div>
                  <div class="like_icon"><img src="{% static 'images/like-icon.png' %}"></div>
                  <p class="post_text">Post By : 09/06/2023</p>
                  <h2 class="most_text">Most Awesome Blue Lake With Snow <br>River</h2>
                  <p class="lorem_text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis</p>
                  <div class="social_icon_main">
                     <div class="social_icon">
                        <ul>
                           <li><a href="#"><img src="{% static 'images/fb-icon.png' %}"></a></li>
                           <li><a href="#"><img src="{% static 'images/twitter-icon.png' %}"></a></li>
                           <li><a href="#"><img src="{% static 'images/instagram-icon.png' %}"></a></li>
                        </ul>
                     </div>
                     <div class="read_bt"><a href="#">Read More</a></div>
                  </div>
               </div>
               <div class="col-lg-4 col-sm-12">
                  <div class="about_main">
                     <h1 class="follow_text">CONNECT & FOLLOW</h1>
                     <div class="follow_icon">
                        <ul>
                           <li><a href="#"><img src="{% static 'images/fb-icon-1.png' %}"></a></li>
                           <li><a href="#"><img src="{% static 'images/twitter-icon-1.png' %}"></a></li>
                           <li><a href="#"><img src="{% static 'images/linkedin-icon-1.png' %}"></a></li>
                           <li><a href="#"><img src="{% static 'images/instagram-icon-1.png' %}"></a></li>
                        </ul>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- blog section end --> 
     
      <!-- copyright section start -->
      <div class="copyright_section">
         <div class="container">
            <p class="copyright_text">Copyright 2023 All Right Reserved By Blogspot</p>
         </div>
      </div>
      <!-- copyright section end -->
      <!-- Javascript files-->
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <script src="{% static 'js/popper.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
      <script src="{% static 'js/plugin.js' %}"></script>
      <!-- sidebar -->
      <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
      <script src="{% static 'js/custom.js' %}"></script>
      <!-- javascript --> 
      <script src="{% static 'js/owl.carousel.js' %}"></script>
      <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
   </body>
</html>

diyblog/templates/blog_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Blog</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
      text-align: center;
    }
    
    h1 {
      margin-top: 20px;
    }
    
    p {
      margin: 0% 10%;
      
     
    }
    
    #comment-box {
      margin-top: 20px;
    }
    
    form {
      display: inline-block;
      text-align: left;
    }
    
    textarea {
      width: 80%;
      box-sizing: border-box;
      margin-bottom: 10px;
    }
    
    button {
      background-color: #4CAF50;
      color: white;
      padding: 10px;
      border: none;
      cursor: pointer;
    }
    
    button:hover {
      background-color: #45a049;
    }
  </style>    
</head>
<body>
  <!-- blog_list.html -->
<!-- blog_detail.html -->
<h1>{{ blog.title }}</h1>
<h3>Author: {{ blog.author }}</h3>
<h3>Date & Time: {{ blog.post_date }}</h3>

<p>{{ blog.content }}</p>
<div id="comment-box">
 
  <!-- Add your comment form here -->
  <form action="#" method="post">
   
    <label for="comment">Comment:</label>
    <textarea id="comment" name="comment" rows="4" required></textarea>

    <button type="submit">Post Comment</button>
  </form>

  <!-- Display existing comments here if needed -->
</div>

</body>
</html>

diyblog/templates/blog_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog List</title>
    <style>
        h1{
            margin-left:45%;
        }
        .card-container {
            display: flex;
            justify-content: space-between; /* Adjust as needed */
        }

        .square-card {
            width: 30%; /* Adjust the width as needed */
            margin: 0% 5% 0%; /* Adjust the margin as needed */
            padding: 10px;
            background-color: black;
            border: 1px solid #ddd;
            border-radius: 8px;
            text-align: center; /* Center the content */
        }
        /* CSS for the black button with white text */
.button-style {
    background-color: white;
    color: black;
    padding: 7px 10px; /* Adjust padding as needed */
    border: none;
    border-radius: 5px; /* Adjust border-radius as needed */
    text-decoration: none; /* Remove underline from the link text */
    display: inline-block;
    font-size: 16px; /* Adjust font-size as needed */
    cursor: pointer;
}


a{
    color:black;
    text-decoration:none;
}
p{
    color:white;
}

    </style>
</head>
<body>
    <!-- HTML structure for three square cards in one row -->
    <h1>Lists of Blog</h1>
    <div class="card-container">
        {% for blog in blogs %}
            <div class="square-card">
                <p>{{ blog.title }}</p>

                <p>{{ blog.author }} </p>
                    <p> {{ blog.post_date }}</p>
                <br>
                <button type="submit" class="button-style"><a href="{% url 'accounts:blog_detail' blog.id %}">View More</a></button>

            </div>
        {% endfor %}
    </div>
</body>
</html>

diyblog/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>Blogspot</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- bootstrap css -->
      <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
      <!-- style css -->
      <link rel="stylesheet" type="text/css" href="{% static 'css/style-index.css' %}">
      <!-- Responsive-->
      <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
      <!-- fevicon -->
      <link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/gif" />
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
      <!-- Tweaks for older IEs-->
      <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
      <!-- owl stylesheets --> 
      <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
      <link rel="stylesoeet" href="{% static 'css/owl.theme.default.min.css' %}">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
   </head>
   <body>
      <!-- header section start -->
      <div class="header_section">
         <div class="container-fluid header_main">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
               <a class="logo" href="#">BLOGSPOT</a>
               <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
               <span class="navbar-toggler-icon"></span>
               </button>
               <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav mr-auto">
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:home' %}">Home</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:post_blog' %}">Post Blog</a>
                     </li>
                     
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:blog_list' %}">Blog</a>
                     </li>
                    
                    
                    
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                     </li>
                    
                  </ul>
               </div>
            </nav>
         </div>
         <!-- banner section start --> 
         <div class="container-fluid">
            <div class="banner_section layout_padding">
               <h1 class="banner_taital">welcome <br>our blog</h1>
               <div id="my_slider" class="carousel slide" data-ride="carousel">
                  <div class="carousel-inner">
                     <div class="carousel-item active">
                        <div class="image_main">
                           <div class="container">
                              <img src="{% static 'images/img-1.png' %}" class="image_1">
                              <div class="contact_bt"><a href="#">Contact Us</a></div>
                           </div>
                        </div>
                     </div>
                     <div class="carousel-item">
                        <div class="image_main">
                           <div class="container">
                              <img src="{% static 'images/img-1.png' %}" class="image_1">
                              <div class="contact_bt"><a href="#">Contact Us</a></div>
                           </div>
                        </div>
                     </div>
                     <div class="carousel-item">
                        <div class="image_main">
                           <div class="container">
                              <img src="{% static 'images/img-1.png' %}" class="image_1">
                              <div class="contact_bt"><a href="#">Contact Us</a></div>
                           </div>
                        </div>
                     </div>
                  </div>
                  <a class="carousel-control-prev" href="#my_slider" role="button" data-slide="prev">
                  <i class="fa fa-angle-left"></i>
                  </a>
                  <a class="carousel-control-next" href="#my_slider" role="button" data-slide="next">
                  <i class="fa fa-angle-right"></i>
                  </a>
               </div>
            </div>
         </div>
         <!-- banner section end --> 
      </div>
      
      <!-- about section start --> 
      <div class="about_section layout_padding">
         <div class="container">
            <div class="row">
               <div class="col-lg-8 col-sm-12">
                  <div class="about_img"><img src="{% static 'images/about-img.png' %}"></div>
                  <div class="like_icon"><img src="{% static 'images/like-icon.png' %}"></div>
                  <p class="post_text">Post By : 09/06/2023</p>
                  <h2 class="most_text">Most Awesome Blue Lake With Snow <br>Mountain</h2>
                  <p class="lorem_text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis</p>
                  <div class="social_icon_main">
                     <div class="social_icon">
                        <ul>
                           <li><a href="#"><img src="{% static 'images/fb-icon.png' %}"></a></li>
                           <li><a href="#"><img src="{% static 'images/twitter-icon.png' %}"></a></li>
                           <li><a href="#"><img src="{% static 'images/instagram-icon.png' %}"></a></li>
                        </ul>
                     </div>
                     <div class="read_bt"><a href="#">Read More</a></div>
                  </div>
               </div>
               <div class="col-lg-4 col-sm-12">
                  <div class="image_5"><img src="{% static 'images/img-5.png' %}"></div>
                  <h1 class="about_taital">About Us</h1>
                  <p class="about_text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis</p>
                  <div class="read_bt_1"><a href="#">Read More</a></div>
               </div>
            </div>
         </div>
      </div>
      <!-- about section end --> 
      <!-- blog section start --> 
      <div class="about_section layout_padding">
         <div class="container">
            <div class="row">
               <div class="col-lg-8 col-sm-12">
                  <div class="about_img"><img src="{% static 'images/img-8.png' %}"></div>
                  <div class="like_icon"><img src="{% static 'images/like-icon.png' %}"></div>
                  <p class="post_text">Post By : 09/06/2023</p>
                  <h2 class="most_text">Most Awesome Blue Lake With Snow <br>River</h2>
                  <p class="lorem_text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis</p>
                  <div class="social_icon_main">
                     <div class="social_icon">
                        <ul>
                           <li><a href="#"><img src="{% static 'images/fb-icon.png' %}"></a></li>
                           <li><a href="#"><img src="{% static 'images/twitter-icon.png' %}"></a></li>
                           <li><a href="#"><img src="{% static 'images/instagram-icon.png' %}"></a></li>
                        </ul>
                     </div>
                     <div class="read_bt"><a href="#">Read More</a></div>
                  </div>
               </div>
               <div class="col-lg-4 col-sm-12">
                  <div class="about_main">
                     <h1 class="follow_text">CONNECT & FOLLOW</h1>
                     <div class="follow_icon">
                        <ul>
                           <li><a href="#"><img src="{% static 'images/fb-icon-1.png' %}"></a></li>
                           <li><a href="#"><img src="{% static 'images/twitter-icon-1.png' %}"></a></li>
                           <li><a href="#"><img src="{% static 'images/linkedin-icon-1.png' %}"></a></li>
                           <li><a href="#"><img src="{% static 'images/instagram-icon-1.png' %}"></a></li>
                        </ul>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
     
      <!-- copyright section start -->
      <div class="copyright_section">
         <div class="container">
            <p class="copyright_text">Copyright 2023 All Right Reserved By Blogspot</p>
         </div>
      </div>
      <!-- copyright section end -->
      <!-- Javascript files-->
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <script src="{% static 'js/popper.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
      <script src="{% static 'js/plugin.js' %}"></script>
      <!-- sidebar -->
      <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
      <script src="{% static 'js/custom.js' %}"></script>
      <!-- javascript --> 
      <script src="{% static 'js/owl.carousel.js' %}"></script>
      <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
   </body>
</html>

diyblog/templates/post_blog.html
<!-- templates/blog/post_blog.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post a Blog</title>
    <style>
       /* Apply basic styling to form elements */
form {
    max-width: 400px; /* Adjust the maximum width as needed */
    margin: auto; /* Center the form horizontally */
}

label {
    display: block; /* Display labels as blocks for better spacing */
    margin-bottom: 5px; /* Add some space below labels */
}

input,
textarea,
select {
    width: 100%; /* Make form controls take full width */
    padding: 8px; /* Adjust padding as needed */
    margin-bottom: 10px; /* Add spacing between form controls */
    box-sizing: border-box; /* Include padding and border in element's total width and height */
}
h2{
    margin-left:45%;
}
button {
    background-color: #000; /* Bootstrap's primary color */
    color: #fff; /* White text color */
    padding: 10px 15px; /* Adjust padding as needed */
    border: none;
    border-radius: 4px;
    cursor: pointer;
}

button:hover {
    background-color: #0056b3; /* Darker color on hover */
}

    </style>
    
</head>
<body>
    <h2>Post a Blog</h2>

    <form method="post" action="{% url 'accounts:post_blog' %}">
        {% csrf_token %}
        
        <label for="title">Title:</label>
        <input type="text" id="title" name="title" required>
        
        <label for="content">Content:</label>
        <textarea id="content" name="content" required></textarea>
        
        <button type="submit">Post Blog</button>
    </form>
</body>
</html>